// ══════════════════════════════════════════
//  i18n dictionary
// ══════════════════════════════════════════

export type StringsDict = {
  [key: string]: string | ((...args: any[]) => string);
};

export const STRINGS: Record<'ja' | 'en', StringsDict> = {
  ja: {
    cmdName:          '盤面検出ビューを開く',
    viewTitle:        'Board Detect',
    settingsTitle:    'Board Detect 設定',
    settingLangName:  '言語',
    settingLangDesc:  'UIの表示言語を選択します',
    langJa:           '日本語',
    langEn:           'English',
    startTitle:       '起動モードを選択',
    btnLoad:          '📂 画像を読み込む',
    btnGen:           '🖼 デフォルト画像生成',
    genColsLabel:     '横 (列)',
    genRowsLabel:     '縦 (行)',
    intersections:    '交点',
    btnGenGo:         '▶ 生成して開始',
    genStoneCount:    '石の数',
    errMaxSize:       'ボードサイズは最大 19 交点です。',
    errMinSize:       'ボードサイズは最小 1 交点です。',
    mainTitle:        '▎ ボード検出',
    labelInput:       '入力画像（元画像）',
    dropZoneText:     'クリックまたはドロップで画像を読み込む',
    cardBoardSize:    '盤面サイズ',
    boardCols:        '横 (列)',
    boardRows:        '縦 (行)',
    cardMargin:       '余白カット（px）',
    imgSizePrefix:    '画像サイズ: ',
    imgSizeSep:       ' × ',
    imgSizeSuffix:    ' px',
    marginTop:        '上 (top)',
    marginBottom:     '下 (bot)',
    marginLeft:       '左 (left)',
    marginRight:      '右 (right)',
    diagTop:          '上',
    diagBottom:       '下',
    diagLeft:         '左',
    diagRight:        '右',
    pxUnit:           'px',
    cardParam:        '判定パラメータ',
    paramBlack:       '黒閾値',
    paramWhite:       '白閾値',
    paramRing:        '輪郭スコア',
    paramHint:        '白石：円周上の暗いピクセル割合 / 空点：低スコア',
    btnDetect:        '▶ 検出実行',
    btnReset:         '再設定',
    // Correction
    btnCorrection:       '✏ 補正',
    btnCorrectionActive: '✏ 補正中（タップで変更 / 再押しでリセット）',
    btnCorrectionHint:   '補正モード：各交点をタップして 黒→白→空→解除 とトグル。再押しで全リセット',
    btnImageOverlay:       '🔍 実画像を重ねる',
    labelOverlayOpacity:  '透明度',
    btnImageOverlayActive: '🔍 実画像を重ねる（表示中）',
    btnImageOverlayHint:   '検出結果の碁盤グラフィックにカット後の実画像を半透明で重ねて表示します',
    labelCropped:     'カット後（盤面のみ）',
    cardResult:       '検出結果',
    cardStats:        '統計',
    statsInitial:     'まだ検出されていません',
    statsBlack:       '黒石',
    statsWhite:       '白石',
    statsNone:        '空点',
    statsTotal:       '合計交点数',
    statsUnit:        '個',
    verifyHeader:     '▎ 検出精度評価（生成ボードとの照合）',
    verifyResult:     (ok: number, total: number, pct: number) => `正解 ${ok} / ${total} 交点 （${pct}%）`,
    verifyNgBlack:    (n: number) => `黒石の誤検出 ${n}件:`,
    verifyNgWhite:    (n: number) => `白石の誤検出 ${n}件:`,
    verifyNgNone:     (n: number) => `空点の誤検出 ${n}件:`,
    verifyPerfect:    '✔ 全交点正解！',
    verifyExpected:   '期待:',
    verifyActual:     '実際:',
    cardExpand:       'ボード展開',
    expandDesc:       '検出結果を大きなボードの指定位置に配置します',
    expandOutCols:    '出力 横',
    expandOutRows:    '出力 縦',
    expandOffX:       'オフセット X',
    expandOffY:       'オフセット Y',
    expandColUnit:    '列',
    expandRowUnit:    '行',
    btnExpand:        '▶ 展開実行',
    errNoDetect:      '先に検出実行してください。',
    errMinOut:        '出力ボードは最小 1 交点です。',
    errMaxOut:        '出力ボードは最大 19 交点です。',
    errOverflowX:     (ox: number, ic: number, oc: number) => `枠超えエラー: X(${ox})+幅(${ic})=${ox+ic} > ${oc}`,
    errOverflowY:     (oy: number, ir: number, or_: number) => `枠超えエラー: Y(${oy})+高さ(${ir})=${oy+ir} > ${or_}`,
    cardExpandResult: '展開結果',
    expandSummary:    (ic: number, ir: number, oc: number, or_: number, ox: number, oy: number) =>
                        `入力: ${ic}×${ir} → 出力: ${oc}×${or_} &nbsp; オフセット: X=${ox}, Y=${oy}`,
    cardSGF:          'SGF 出力',
    sgfPLLabel:       '初手',
    sgfPLBlack:       '黒先',
    sgfPLWhite:       '白先',
    sgfPLInfoBlack:   '● 黒先',
    sgfPLInfoWhite:   '○ 白先',
    sgfGMLabel:       'ゲームモード',
    sgfRULabel:       'ルール',
    sgfGMGo:          '囲碁',
    sgfGMRenju:       '連珠 / 五目',
    sgfRUPlaceholder: 'Puzzle info（省略可）',
    btnMakeSGF:       '▶ SGF 作成',
    sgfTextLabel:     'SGF テキスト',
    btnCopy:          '📋 コピー',
    btnSaveVault:     '💾 Vaultに保存',
    copyDone:         '✔ コピーしました',
    saveDone:         (f: string) => `✔ ${f} に保存`,
    errNoSGF:         '先にSGFを作成してください。',
    saveOK:           (f: string) => `SGFを保存しました: ${f}`,
    saveErr:          (e: unknown) => `保存エラー: ${e}`,
    noticeMarginTooLarge: '余白が大きすぎます',
    noticeNoExpand:   '先に展開実行してください。',
    // Reset confirmation
    savePngConfirmTitle: '画像の作成',
    savePngConfirmMsg:   'ボードの画像をPNGファイルとして保存しますか？',
    savePngOk:           '保存',
    savePngIncludeMarkers: 'マーカーを含める',
    savePngIncludeBorder:  '座標を含める',
    resetConfirmTitle:  'リセットの確認',
    resetConfirmMsg:    '本当にリセットしますか？\n現在の検出結果・設定がすべてクリアされます。',
    resetConfirmOk:     'リセット',
    resetConfirmCancel: 'キャンセル',
    // Settings - color reset
    btnResetColor:      'デフォルトに戻す',
    // Marker size UI (main view)
    labelMarkerSize:    'マーカーサイズ',
    lastMoveColor:            '最終手マーカー色',
    sgfMarkerColor:           'シンボルマーカー色（石上）',
    sgfMarkerEmptyColor:      'シンボルマーカー色（空点上）',
    moveNumBlackStoneColor:   '手順番号色（黒石上）',
    moveNumWhiteStoneColor:   '手順番号色（白石上）',
    markerSizeUnit:     '% (石サイズ比)',
    // Visual settings
    settingVisualTitle:       '表示設定',
    settingBoardBgName:       '盤面の背景色',
    settingBoardBgDesc:       '検出結果・展開結果のボード背景色を指定します',
    settingMarkerBlackName:   '黒石マーカー色',
    settingMarkerBlackDesc:   '検出画像に重ねる黒石検出マーカー色',
    settingMarkerWhiteName:   '白石マーカー色',
    settingMarkerWhiteDesc:   '検出画像に重ねる白石検出マーカー色',
    settingMarkerSizeName:    'マーカーサイズ（%）',
    settingMarkerSizeDesc:    '検出画像のマーカー半径をグリッド1マスに対する割合で指定します（例: 50 = 1マスの50%）',
    sgfModeLabel:       'モード',
    showMoveNum:        '手順表示',
    sgfModeRef:         '参照',
    sgfModePlay:        'Play',
    sgfModeEdit:        '編集',
    sgfBtnFirst:        '⏮ 最初',
    sgfBtnLast:         '⏭ 最後',
    sgfBtnPrev:         '◀ 前',
    sgfBtnNext:         '次 ▶',
    sgfBtnPlayPrev:     '◀ 戻る',
    sgfBtnPlayNext:     '進む ▶',
    sgfTurnBlack:       '● 黒番',
    sgfTurnWhite:       '○ 白番',
    sgfBtnCopy:         '📋 コピー',
    sgfBtnCopied:       '✓ コピー済み',
    sgfBtnCopyErr:      '✗ エラー',
  },

  en: {
    cmdName:          'Open Board Detect view',
    viewTitle:        'Board Detect',
    settingsTitle:    'Board Detect Settings',
    settingLangName:  'Language',
    settingLangDesc:  'Select the display language for the UI',
    langJa:           '日本語',
    langEn:           'English',
    startTitle:       'Select startup mode',
    btnLoad:          '📂 Load image',
    btnGen:           '🖼 New sample board',
    genColsLabel:     'Columns',
    genRowsLabel:     'Rows',
    intersections:    'intersections',
    btnGenGo:         '▶ Generate & start',
    genStoneCount:    'Stone count',
    errMaxSize:       'Board size must be 19 intersections or fewer.',
    errMinSize:       'Board size must be at least 1 intersection.',
    mainTitle:        '▎ BOARD DETECTOR',
    labelInput:       'Source image',
    dropZoneText:     'Click or drop to load another image',
    cardBoardSize:    'Board size',
    boardCols:        'Columns',
    boardRows:        'Rows',
    cardMargin:       'Margin crop (px)',
    imgSizePrefix:    'Image size: ',
    imgSizeSep:       ' × ',
    imgSizeSuffix:    ' px',
    marginTop:        'Top',
    marginBottom:     'Bottom',
    marginLeft:       'Left',
    marginRight:      'Right',
    diagTop:          'T',
    diagBottom:       'B',
    diagLeft:         'L',
    diagRight:        'R',
    pxUnit:           'px',
    cardParam:        'Detection parameters',
    paramBlack:       'Black thresh',
    paramWhite:       'White thresh',
    paramRing:        'Ring score',
    paramHint:        'White stones: dark pixel ratio on circumference / Empty: low score',
    btnDetect:        '▶ Detect',
    btnReset:         'Re-setup',
    // Correction
    btnCorrection:       '✏ Correct',
    btnCorrectionActive: '✏ Correcting (tap to toggle / press again to reset)',
    btnCorrectionHint:   'Correction mode: tap each intersection to cycle Black→White→Empty→Auto. Press again to reset all.',
    btnImageOverlay:       '🔍 Overlay image',
    labelOverlayOpacity:  'Opacity',
    btnImageOverlayActive: '🔍 Overlay image (ON)',
    btnImageOverlayHint:   'Overlay the cropped board image semi-transparently onto the detection result graphic',
    labelCropped:     'Cropped (board only)',
    cardResult:       'Detection result',
    cardStats:        'Statistics',
    statsInitial:     'No detection yet',
    statsBlack:       'Black',
    statsWhite:       'White',
    statsNone:        'Empty',
    statsTotal:       'Total intersections',
    statsUnit:        '',
    verifyHeader:     '▎ Accuracy check (vs. generated board)',
    verifyResult:     (ok: number, total: number, pct: number) => `Correct: ${ok} / ${total} (${pct}%)`,
    verifyNgBlack:    (n: number) => `Black misdetections (${n}):`,
    verifyNgWhite:    (n: number) => `White misdetections (${n}):`,
    verifyNgNone:     (n: number) => `Empty misdetections (${n}):`,
    verifyPerfect:    '✔ All intersections correct!',
    verifyExpected:   'expected:',
    verifyActual:     'actual:',
    cardExpand:       'Board expand',
    expandDesc:       'Place detection result onto a larger board at a specified offset.',
    expandOutCols:    'Output cols',
    expandOutRows:    'Output rows',
    expandOffX:       'Offset X',
    expandOffY:       'Offset Y',
    expandColUnit:    'col',
    expandRowUnit:    'row',
    btnExpand:        '▶ Expand',
    errNoDetect:      'Please run detection first.',
    errMinOut:        'Output board must be at least 1 intersection.',
    errMaxOut:        'Output board must be 19 intersections or fewer.',
    errOverflowX:     (ox: number, ic: number, oc: number) => `Overflow: X(${ox})+W(${ic})=${ox+ic} > ${oc}`,
    errOverflowY:     (oy: number, ir: number, or_: number) => `Overflow: Y(${oy})+H(${ir})=${oy+ir} > ${or_}`,
    cardExpandResult: 'Expand result',
    expandSummary:    (ic: number, ir: number, oc: number, or_: number, ox: number, oy: number) =>
                        `Input: ${ic}×${ir} → Output: ${oc}×${or_} &nbsp; Offset: X=${ox}, Y=${oy}`,
    cardSGF:          'SGF output',
    sgfPLLabel:       'First move',
    sgfPLBlack:       'Black first',
    sgfPLWhite:       'White first',
    sgfPLInfoBlack:   '● Black first',
    sgfPLInfoWhite:   '○ White first',
    sgfGMLabel:       'Game mode',
    sgfRULabel:       'Rules',
    sgfGMGo:          'Go',
    sgfGMRenju:       'Renju / Gomoku',
    sgfRUPlaceholder: 'Puzzle info (optional)',
    btnMakeSGF:       '▶ Create SGF',
    sgfTextLabel:     'SGF text',
    btnCopy:          '📋 Copy',
    btnSaveVault:     '💾 Save to Vault',
    copyDone:         '✔ Copied',
    saveDone:         (f: string) => `✔ Saved to ${f}`,
    errNoSGF:         'Please create the SGF first.',
    saveOK:           (f: string) => `SGF saved: ${f}`,
    saveErr:          (e: unknown) => `Save error: ${e}`,
    noticeMarginTooLarge: 'Margin is too large.',
    noticeNoExpand:   'Please run expand first.',
    // Reset confirmation
    savePngConfirmTitle: 'Save image',
    savePngConfirmMsg:   'Save the board as a PNG file?',
    savePngOk:           'Save',
    savePngIncludeMarkers: 'Include markers',
    savePngIncludeBorder:  'Include coordinates',
    resetConfirmTitle:  'Confirm reset',
    resetConfirmMsg:    'Are you sure you want to reset?\nAll current detection results and settings will be cleared.',
    resetConfirmOk:     'Reset',
    resetConfirmCancel: 'Cancel',
    // Settings - color reset
    btnResetColor:      'Reset to default',
    // Marker size UI (main view)
    labelMarkerSize:    'Marker size',
    lastMoveColor:            'Last move marker color',
    sgfMarkerColor:           'Symbol marker color (on stone)',
    sgfMarkerEmptyColor:      'Symbol marker color (on empty)',
    moveNumBlackStoneColor:   'Move number color (on black stone)',
    moveNumWhiteStoneColor:   'Move number color (on white stone)',
    markerSizeUnit:     '% (of stone)',
    // Visual settings
    settingVisualTitle:       'Visual settings',
    settingBoardBgName:       'Board background color',
    settingBoardBgDesc:       'Background color for the result and expanded board',
    settingMarkerBlackName:   'Black stone marker color',
    settingMarkerBlackDesc:   'Color of the overlay marker for detected black stones',
    settingMarkerWhiteName:   'White stone marker color',
    settingMarkerWhiteDesc:   'Color of the overlay marker for detected white stones',
    settingMarkerSizeName:    'Marker size (%)',
    settingMarkerSizeDesc:    'Marker radius as a percentage of one grid cell (e.g. 50 = 50% of one cell)',
    sgfModeLabel:       'Mode',
    showMoveNum:        'Show move numbers',
    sgfModeRef:         'View',
    sgfModePlay:        'Play',
    sgfModeEdit:        'Edit',
    sgfBtnFirst:        '⏮ First',
    sgfBtnLast:         '⏭ Last',
    sgfBtnPrev:         '◀ Prev',
    sgfBtnNext:         'Next ▶',
    sgfBtnPlayPrev:     '◀ Prev',
    sgfBtnPlayNext:     'Next ▶',
    sgfTurnBlack:       '● Black',
    sgfTurnWhite:       '○ White',
    sgfBtnCopy:         '📋 Copy',
    sgfBtnCopied:       '✓ Copied',
    sgfBtnCopyErr:      '✗ Error',
  },
};
